### ISSUE TITLE
Arbitrary Radicle values that are stable under JSON serialisation

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/oscoin#258]
Currently, if we create an arbitrary Radicle value, serialise it to JSON and parse it from JSON we might get a different representation of the same value back. That is the following property does not hold
~~~hs
Aeson.decode (Aeson.encode radValue) === Just radValue
~~~

**Comment by adinapoli-mndc** [comment]
This can be closed as Radicle is not part of `oscoin` anymore.
