### ISSUE TITLE
Remove `once` calls in test suite

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/oscoin#369]
As an interim measure for https://github.com/oscoin/oscoin/pull/366 , we placed a number of calls to `once` in the test suite which is limiting the number of QC runs to only 1. This is detrimental for the kind of property-based testing QC shines on. The reason we did that was to overcome the fact our test suite is growing slower due to the use of a lot of cryptographic primitives (hashing primarily).

In order to fix this ticket, we should first remove the roadblock preventing us from actually speeding up the tests, which is logged under https://github.com/oscoin/oscoin/issues/368

**Comment by adinapoli-mndc** [comment]
I have started investigating this as a natural successor of #368. In particular, once I re-enabled the full 100+ QC runs, the running times (with `MockCrypto` !) inflated to like 300+ seconds o.O. I did hit the code with profiling and two things stood out:

1. From my first profiling, a lot of time was spent calling [thisPos](https://github.com/oscoin/radicle/blob/ce65e49ae3023ae0caefaa83745ff02894a50458/src/Radicle/Internal/Annotation.hs#L58) from this [Arbitrary instance](https://github.com/oscoin/oscoin/blob/master/test/Oscoin/Test/Data/Rad/Arbitrary.hs#L37) and is not totally clear to me why we are doing all of that (mostly because I am a Radicle n00b):

<img width="1906" alt="screenshot 2019-03-05 at 12 03 52" src="https://user-images.githubusercontent.com/45846748/53816601-17cb7500-3f64-11e9-9ad4-3c1f61bd9959.png">

@cloudhead , do you have any insights on the above?

2. After commenting out that tagging/untagging shenanigans (leaving only `sized go` in place) lots of tests would fail, but the next profiling would reveal that a significant chunk of time was spent in `serialise` when calling `hashTxs`.

<img width="1906" alt="screenshot 2019-03-05 at 12 11 02" src="https://user-images.githubusercontent.com/45846748/53816735-624cf180-3f64-11e9-8baf-554ad36f279b.png">

We were chatting about 2. with @kim and we were thinking that perhaps (actually, quite likely) what is biting us is the generic deriving for those `Serialise` instances. Handy for sure, but it's pretty common that these automatically-derived instances comes with a performance cost.

I would propose the tentative plan of action for this ticket:

- [ ] Investigate how we can speed up the generation of `Arbitrary` Rad's `Value`s;
- [ ] Generate the `Serialise` instances by hand, and create for each and every instance a roundtrip property, painful but necessary (it can be automated though, see for example [here](https://github.com/input-output-hk/cardano-sl/blob/develop/core/test/Test/Pos/Core/CborSpec.hs#L82-L109) 
- [ ] Remove the `once` combinator and hopefully watch those tests run very quickly.

Wdyt?

**Comment by adinapoli-mndc** [comment]
Ok, concretely, this is my "plan of attack" for this morning. We have one test which is very, very slow once we remove the `once` call. Look at this guy:

<img width="950" alt="screenshot 2019-03-06 at 09 44 17" src="https://user-images.githubusercontent.com/45846748/53867599-7cceab80-3ff4-11e9-8a95-171911617b7b.png">

(Full disclosure: I am running only 50 tests and using a predictable seed to get semi-predictable performances). Something is off here, almost 300 seconds seems to be too much of a punishment for such a simple operation. I will now try to see if I can unroll the `Serialise` instances this test uses and observe the performance impact. I will also have another round with `profiteur` to make sure I am flogging a dead horse and the perf bottleneck is elsewhere.

**Comment by cloudhead** [comment]
Surely this is slow because you are running a profiler?

**Comment by cloudhead** [comment]
I would not spend too much energy on making the Radicle bits faster, as we are likely to take that piece out after our decision on smart contracts. Otherwise, sounds like a great plan :+1:

**Comment by adinapoli-mndc** [comment]
> Surely this is slow because you are running a profiler?

Alas those times were for the non-profile code 😢 there is a _real_ slowdown here, it's simply not clear to me yet which is the culprit.

> I would not spend too much energy on making the Radicle bits faster, as we are likely to take that piece out after our decision on smart contracts.

Agreed. We concluded pretty much the same thing with @kim after a quick chat today. We are still interested (for post-mortem reasons) to understand _why_ the slowdown was there in the first place, but I think we all agree that removing crafty arbitrary instances for a `Rad.Value` might be the path of least resistance as is likely the entire Radicle library will be evicted from `oscoin`.

**Comment by adinapoli-mndc** [comment]
Small update from an unproductive day where I shifted a bunch of code around trying to get to the bottom of this performance bottleneck. It turns out that `Arbitrary ByteString` is slow and "considered harmful(TM): https://github.com/nick8325/quickcheck/issues/234

In that same ticket phadej proposes a patch to `quickcheck-instances` that sped things up quite sensibly. I will have to revisit this in the morning with a less-butchered code.

Something is true regardless, though: we generate random `ByteString` s in a bunch of places, including (this is key, no pun intended) in our mock implementation of the digital signature, as that relies on xoring bytestrings together. This could justify the slowness, as every Tx we generate needs to be signed (well, its `txMessage` anyway).

**Comment by adinapoli-mndc** [comment]
Fixed by https://github.com/oscoin/oscoin/pull/400
