### ISSUE TITLE
Move to new Tx type

### ISSUE THREAD

**Issue by cloudhead** [oscoin/oscoin#404]
Now that we have an idea on how we will do smart contracts, we should:

* [x] Remove the dependency to Radicle, along with all code relating to it. (@geigerzaehler)
* [ ] ~~Move to an ADT for `Tx`, with all the available transactions. (@geigerzaehler)~~
* [ ] ~~Fix Tx signing, so that the entire Tx is signed. (@geigerzaehler)~~
* [ ] ~~Move state from `Rad.Env` to `State.Tree` (@geigerzaehler)~~
* [ ] ~~Use `avl-auth` for state storage, instead of `Map` (@cloudhead)~~

**Comment by geigerzaehler** [comment]
Tasks are either done or outdated and superseded by other tasks. Closing...
