### ISSUE TITLE
Move Args parser into its own module

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/oscoin#427]
This voices the concern raised [here](https://github.com/oscoin/oscoin/pull/426#issue-263548725). Essentially our `Args` parser in `exe/Main.hs` is growing a bit out of control, and I think it's time to move it in a standalone module.

@kim suggested we move everything into the library, as that would allow us to write better and more specific tests.

**Comment by kim** [comment]
I wonder if it would make sense to consolidate stuff like `Environment`, `Network` (cf. #419), the genesis YAML format, and option parsing under the same hierarchy, or even module. `Oscoin.Configuration`, for example.

**Comment by adinapoli-mndc** [comment]
I like the idea of having an `Oscoin.Configuration` module, it matches my idea that you have to plug these different lego pieces under a common umbrella to be able to fully "qualify" a node.
