### ISSUE TITLE
Add the block height to each block header

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/oscoin#497]
## Problem

Sooner rather than later, when our devnet will be launched, nodes will need to start communicating between each other not just to exchange blocks, but also to sync themselves up, from genesis to to the tip of the blockchain. Why this is important is quite obvious: all the nodes need to have the same, consistent view of the world in order to operate. Some blockchains might impose a node to be 100% synced for certain operations to be possible, other might simply require things to be up-to-date up to a point. Not only that, but it might be quite handy for apps built on-top of a node, to have access to an API call like `/api/node/sync_progress` to get back the sync percentage, as well as the ETA for a full sync.

In a standard gossip setting, nodes would forward blocks to their closest peers when they create/receive them, but that works well only if all the nodes starts from the same block, and works a bit less well if a node is proactively trying to sync. In such scenario, a node would ideally like to request "all the blocks from genesis up to this block I have just received" or again "please send me all the blocks between X and Y".  However, in our current implementation doing that is not easy, because:

1. One cannot use the `Difficulty` to pinpoint block ranges, as that is not monotonically increasing and is subject to swings (it increases/stays the same/decreases every 2016 blocks);

2. Block hashes are not a very good candidate for that, as it doesn't exist a meaningfully ordering between them. A node cannot simply ask "give me all the nodes between `0befa98` and `0cadd97`). 

## Solution

*I propose to add the block height to the block header*.  This is something we talked about in the past, and that (I think) BTC also does (but they include the height in the coinbase transaction). This has several advantages:

* It allows for efficient queries in a relational database who has an index on the block height;
* It helps resolving https://github.com/oscoin/oscoin/issues/353 (where we had trouble with implementing pagination efficiently otherwise);
* It should fix https://github.com/oscoin/oscoin/issues/331 ;
* It will make node syncing (allegedly) more efficient. For example, each node could cache the "highest block" (that it receives unsolicited) and compute a diff between its current height (i.e. height of the current tip) vs its "best height" and then request via gossip those block(headers).
* Computing a node sync percentage is very easy now, it's essentially `last_known_best_height / local_height * 100`

### Implementation plan

We will need to extend the `BlockHeader` with the height, and thread the changes throughout the codebase. The SQLite `BlockStore` (internals) will also need some tweaking. Assuming we mine a block every minute (is this a reasonable assumption?) we can use a `Word32` to store the height (_thus inflating the block header by 4 bytes_), as with `maxBound` 4294967295 minutes we can cover ~8000 years worth of blockchain history.

## (Optional) Alternative solutions considered

The alternatives would be:

1. Always compute the `height` on-the-fly, assuming that doing that is inexpensive and doesn't compromise our chances of syncing efficiently;

Having said that, the `height` seems something universally useful to store, so perhaps we should bite the bullet.

@cloudhead @kim @geigerzaehler thoughts?

**Comment by kim** [comment]
+1

**Comment by geigerzaehler** [comment]
> Block hashes are not a very good candidate for that, as it doesn't exist a meaningfully ordering between them. A node cannot simply ask "give me all the nodes between `0befa98` and `0cadd97`).

I would beg to differ. I think we can implement blockhash based querying by storing the block height in the database but not in the header.

Let’s consider the following example: Node A has been down for a while and now starts up again. The first block it receives is `0cc`, the most recent block it has in its blockchain is `0aa`. It asks the network to give it every block between `0aa` and `0cc`. A node B that receives this request takes a look in its database and checks that it has blocks `0cc` and `0aa` in its database. Since node B also stores the height in the database (calculating it on insert) it can get easily make an SQL query that retrieves all blocks between `0aa` and `0cc` and returns them to node A.

**Comment by kim** [comment]
@geigerzaehler It's technically possible, but I think the argument is that it's much more _convenient_ to just use the height (which happens to have a total ordering, think `ORDER BY`).

**Comment by adinapoli-mndc** [comment]
> which happens to have a total ordering

@geigerzaehler Right, as you pointed out that is possible but that's a huge hack based on the fact we required an `Ord` instance on `Hash a` based on the lexicographical order of the hashes, which is meaningless and not very efficient 😁

**Comment by cloudhead** [comment]
:+1: - the only downside is increase in block header size, but at only 8 bytes for a Word64, it's not a big concern.

**Comment by cloudhead** [comment]
Actually 32 bits would give us 7000 years of blocks :thinking:

**Comment by adinapoli-mndc** [comment]
@cloudhead as written above (looks like somebody was too tired to read exhaustively? :trollface: )

> we can use a Word32 to store the height (thus inflating the block header by 4 bytes), as with maxBound 4294967295 minutes we can cover ~8000 years worth of blockchain history

😬

**Comment by geigerzaehler** [comment]
> @geigerzaehler Right, as you pointed out that is possible but that's a huge hack based on the fact we required an `Ord` instance on `Hash a` based on the lexicographical order of the hashes, which is meaningless and not very efficient 😁

This “hack” does not need an `Ord` instance on `Hash a`. We use the height for ordering but compute it when inserting it in the database so there is no need to include it in the block header.

**Comment by adinapoli-mndc** [comment]
Sorry, wasn't suggesting that your proposal was a _hack_ (would never dare to do it!) but rather pointing out that the fact we sort & compare hashes is a bit of an unfortunate evil and if we can avoid that it's surely good from a design perspective 🙂 

> We use the height for ordering but compute it when inserting it in the database so there is no need to include it in the block header.

What I am concerned here is unsolicited blocks -- if you receive an unsolicited block from the gossip layer, you wouldn't know _apriori_ which is its height (if you don't store this info in the header), therefore you cannot request blocks based on heights, but you would need to request batches based on hash ranges (like your original proposal). But this is a bit restrictive, because you know the lower & upper bounds hashes but not the hashes "in the middle", so the gossip layer cannot distribute work between peers in case it wants to (for example by requesting blocks 0 ... 100 from one peer and 101 .. 200 from another etc). In the case of a cold sync, where you might be at genesis and you receive (unsolicited) the tip of the chain, parallelising download this way might be nice.

Am I making sense or do I need another cup of ☕️ ? 🙈

**Comment by geigerzaehler** [comment]
>  so the gossip layer cannot distribute work between peers in case it wants to (for example by requesting blocks 0 ... 100 from one peer and 101 .. 200 from another etc).

:bulb: This indeed does not work with hashes. But since this is only required for a cold sync maybe an (imperfect) heuristic based on block timestamps would be good enough to distribute the request?

**Comment by cloudhead** [comment]
> @cloudhead as written above (looks like somebody was too tired to read exhaustively? :trollface: )
> 
> > we can use a Word32 to store the height (thus inflating the block header by 4 bytes), as with maxBound 4294967295 minutes we can cover ~8000 years worth of blockchain history

:sleeping_bed:

**Comment by cloudhead** [comment]
> Let’s consider the following example: Node A has been down for a while and now starts up again. The first block it receives is `0cc`, the most recent block it has in its blockchain is `0aa`. It asks the network to give it every block between `0aa` and `0cc`. A node B that receives this request takes a look in its database and checks that it has blocks `0cc` and `0aa` in its database. Since node B also stores the height in the database (calculating it on insert) it can get easily make an SQL query that retrieves all blocks between `0aa` and `0cc` and returns them to node A.

@geigerzaehler I'm not sure I understand the significance of a hash range here. Why would there have to be blocks between `0aa` and `0cc`?

**Comment by geigerzaehler** [comment]
> @geigerzaehler I'm not sure I understand the significance of a hash range here. Why would there have to be blocks between `0aa` and `0cc`?

Sorry that this is a bit unclear. What I meant was that a node is looking for all blocks in a blockchain between the block with hash `0aa` and the block with hash `0cc`.

**Comment by adinapoli-mndc** [comment]
What's the final verdict on this ticket? @geigerzaehler do you have any strong objections which might lead to vetoing this proposal or (as me, Kim and Alexis are happy with it) are you fine with me start working on it?

**Comment by geigerzaehler** [comment]
I agree with this proposal, too. @cloudhead raised an important point. Most major blockchains include the block header so there might be additional benefits to this that we did not discover and consider yet.

**Comment by adinapoli-mndc** [comment]
Great! 🎉 I volunteer to pick this up, unless somebody would strongly like to work on it instead 😉

**Comment by adinapoli-mndc** [comment]
Fixed by https://github.com/oscoin/oscoin/pull/522 and #514.
