### ISSUE TITLE
Schnorr signatures

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/oscoin#498]
## Problem

Space on-chain is precious, and ECDSA suffers from two main problems:

* ECDSA signatures are [malleable](https://en.wikipedia.org/wiki/Malleability_(cryptography));
* Their size in bytes is variable.

## Solution/implementation plan

Switch to use [Schnorr signatures](https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki), that produces constant-sized 64-bytes signatures and are not malleable. On top of that, it allows multiple signatures to be combined together (without changing the final size) and therefore this makes it an excellent candidate for multi-sig schemes like [muSig](https://eprint.iacr.org/2018/068).

I have done a bit of research last week on the topic and from my understanding there are various components at play here:

1. There is the [original '91 paper](https://www.researchgate.net/profile/Claus_Schnorr/publication/227088517_Efficient_signature_generation_by_smart_cards/links/0046353849579ce09c000000.pdf) which is described in fairly generic algebraic groups and hashing functions;

2. The linked BIP proposal that specialises it for ECC (i.e. elliptic-curves-cryptography)

3. zero-knowledge protocols _based_ on Schnorr like [this](https://github.com/adjoint-io/schnorr-nizk) which I don't think they are useful to us.  

## Risks & unknowns

Something that it should be pointed out is that [EdDSA](https://github.com/haskell-crypto/cryptonite/issues/120#issuecomment-266657040) (that `cryptonite` implements) it's _based_ on Schnorr signatures , and it's likely what we are using at the moment. On top of that, if one goes and read the [RFC](https://tools.ietf.org/html/rfc8032) it's quite apparent (by looking at the [test vectors](https://tools.ietf.org/html/rfc8032#section-7)) that the signature size is pretty much the same as produced by the linked BIP (the curve we are interested is Ed25519). Therefore, one of the strong selling point of the BIP (i.e. space efficiency) doesn't seem to be an issue in our current implementation. Furthermore, the BIP seems to lock us into using a message of _fixed_ size (which is probably either the hash of some state or a merkle root hash), which is a bit limiting, frankly. 

What needs to be assessed though it's the malleability + composability properties, which might tip the scale towards implementing the BIP proposal vs keeping the current status quo. 

## (Optional) Alternative solutions considered

I haven't explored the domain long enough, but this seems to be what the state-of-the-art seems to be rapidly heading. Question remains around the proposal vs what we are using at the moment.

@kim @cloudhead @geigerzaehler thoughts?

**Comment by geigerzaehler** [comment]
Do I understand this correctly that the implementation would only require us to switch from `Crypto.PubKey.ECC.ECDSA` to `Crypto.PubKey.Ed25519`?

**Comment by adinapoli-mndc** [comment]
> Do I understand this correctly that the implementation would only require us to switch from Crypto.PubKey.ECC.ECDSA to Crypto.PubKey.Ed25519?

If we can check that `Ed25519` is not subject to malleability, it always produced fixed-size signatures and it has this nice combining property needed for multisigs then yes, but all means the "implementation" it's one a one liner 😁 

Conversely, if we think `Ed25519` doesn't tick all the boxes, then perhaps we don't have any better choice than to try implement the BIP proposal.

**Comment by geigerzaehler** [comment]
I would like to understand the problems outlined in this issue better:

Could you please elaborate what transaction malleability means and why it is an issue? ECDSA does no suffer from the general malleability described in the linked Wikipedia article and it can easily be adjusted to be non-malleable ([CIP62](https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki#low-s-values-in-signatures). Moreover I think that the malleability only poses a problem because of signature being part of the Bitcoin Script code.

I would like to challenge that a variable size for signatures is a problem as you mentioned yourself in “risks and unknowns”. The issue with ECDSA is the large size.

Finally, I don’t think we should implement the Schnorr BIP ourselves. In fact, we should not implement any cryptographic primitives ourselves but rather rely on peer-reviewed solutions by cryptography experts.

**Comment by adinapoli-mndc** [comment]
> Could you please elaborate what transaction malleability means and why it is an issue?

I am no crypto expert, but I am merely referring to one of the motivations in the BIP proposal:

> Non-malleability: ECDSA signatures are inherently malleable; a third party without access to the private key can alter an existing valid signature for a given public key and message into another signature that is valid for the same key and message. This issue is discussed in BIP62 and BIP66. On the other hand, Schnorr signatures are provably non-malleable.[1]

> I would like to challenge that a variable size for signatures is a problem as you mentioned yourself in “risks and unknowns”. The issue with ECDSA is the large size.

Sorry, I was not clear enough in my writeup -- the fact they are variable in size is not a problem per se, but as the BIP points out "Instead of DER-encoding for signatures (which are variable size, and up to 72 bytes), we can use a simple fixed 64-byte format." i.e. in the worst case scenario ECDSA signatures might be less compact than the Schnorr counterpart (at least from my own understanding).

> Finally, I don’t think we should implement the Schnorr BIP ourselves. In fact, we should not implement any cryptographic primitives ourselves but rather rely on peer-reviewed solutions by cryptography experts.

This is not necessary what I am proposing (indeed, never ever ever roll out your own crypto!) but if I have understood the gist of the proposal it's based on ECC cryptography anyway so you can reuse the lego building blocks provided by crypto experts and add the digital signature scheme on top of that. Obviously the best scenario would be for us to find a peer reviewed C library we can bind to (unless the `cryptonite` folks are willing to implement it, we can ask).

**Comment by cloudhead** [comment]
:+1: it was always the plan to switch to a more modern signature scheme. Most quality crypto projects out there are moving to schnorr, because it's not only more efficient and secure, but also allows for easy aggregation, as you say, which can dramatically reduce block size and allow better privacy for multi-sig. It essentially makes single-sig and multi-sig indistinguishable.

There's a nice analysis here, by one of the web3 cryptographers, explaining why they went for Schnorr, albeit not with Ed25519: https://forum.web3.foundation/t/account-signatures-and-keys-in-polkadot/70/3

**Comment by cloudhead** [comment]
One question I have is what alternatives to EdDSA exist - I don't hear about it often, and I don't know what implementation of Schnorr was chosen for Bitcoin. Any ideas?

**Comment by adinapoli-mndc** [comment]
> One question I have is what alternatives to EdDSA exist - I don't hear about it often, and I don't know what implementation of Schnorr was chosen for Bitcoin. Any ideas?

Good question -- we should probably probe the ground (both in terms of academic papers and other cryptocurrencies) and see what does fit best, being aware that the more exotic and obscure we go, the bigger the risk of not finding high-quality implementation we can bind to (cfr. @geigerzaehler concern to never roll our own crypto 😁 ).

Cardano, for example, uses EdDSA afaik (and [this article](https://medium.com/unraveling-the-ouroboros/schnorr-signatures-e5218d1ade9f) claims the same). For such a delicate topic my gut feeling is that we shouldn't try to "innovate" but rather stand on the shoulder of the giants, but doing research is already a good thing to do before head-diving into a ticket 😀

**Comment by cloudhead** [comment]
From my research, Blockstream's `MuSig` is how they plan to do signature aggregation. This doesn't seem to be possible with vanilla EdDSA, or at least with what's available in cryptonite. There is a rust implementation here: https://github.com/w3f/schnorrkel which I think is intended to be used for Polkadot.

If we switch to EdDSA and Ed25519, it's probably a good first step, but we won't get multi-sig until we implement a proper scheme such as MuSig :disappointed:

**Comment by geigerzaehler** [comment]
> If we switch to EdDSA and Ed25519, it's probably a good first step

I agree. EdDSA is standardized and well researched. It also satisfies properties listed in the issue’s description. Plus, them an implementation of Ed25519 is available in cryptonite.
