### ISSUE TITLE
Modify the serialisation of an AddressPayload

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/oscoin#504]
## Problem

If we want to tackle https://github.com/oscoin/oscoin/issues/498 and switch to `Ed25519`, we won't be able to perform `PublicKey` recovery from a transaction unless we either embed the `PublicKey` into the `Tx` itself or we make the `PublicKey` recoverable from an `Address`. In the current design, however, this is not possible as we store inside the `AddressPayload` the (short) hash of a public key. 

## Solution/implementation plan

_Use CBOR to serialise the `PublicKey` into the `AddressPayload`_. This doesn't create any security hazard (a `PublicKey` is meant to be public, after all) at the cost of a small increase in size for the overall `Address` (to quantify when working on the PR).

## (Optional) Alternative solutions considered

The alternative solution would be to bake the `PublicKey` into each `Tx`, but @kim raised some good concerns here [already](https://github.com/oscoin/oscoin/pull/477), advocating against this approach.

cc @cloudhead @geigerzaehler

**Comment by cloudhead** [comment]
:+1: - looking at other high quality projects with Ed25519 + accounts, they are doing something very similar, eg. in substrate: https://wiki.parity.io/Extrinsic
