### ISSUE TITLE
Use a bloom filter in the P2P layer to deal with seen messages

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/oscoin#512]
Gossip deals with _seen messages_, so it should be _all_ blocks seen so far. As mentioned before, this should be handled by a bloom filter maintained by the gossip layer, not read-through to storage.

_Originally posted by @kim in https://github.com/oscoin/oscoin/pull/509_

**Comment by geigerzaehler** [comment]
@adinapoli-mndc: Does this need to be part of the devnet?

**Comment by adinapoli-mndc** [comment]
We discussed this with @cloudhead the other day; I would defer on what @kim thinks, but my opinion is that this would definitely be a nice to have, but is not strictly required.

**Comment by kim** [comment]
I am not sure this is safe to do with the node syncing stuff, which rests on the assumption of an anti-entropy mechanism on the gossip layer. The correctness depends on data retention in the event of switching forks - if consensus switches to a fork and throws away data, but later switches back to the original chain (for which now blocks are missing), the states diverge.

We should probably not do this until fork selection is better understood and specified.
