### ISSUE TITLE
Expose getPeers in Oscoin.P2P

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/oscoin#533]
This stems from a discussion between me and @kim as I was doing some exploratory research for #531. Regardless which syncing strategy we chose, something is quite clear: we don't want to leak implementation details of the gossip layer to whichever process will run the syncing. Not only that, but gossip is all about broadcasting messages and is not really suited for this kind of "point-2-point" conversations, also because the gossip layer could evict a peer at any given time.

To mitigate this, a solution we are discussing is to grab the active view from the underlying membership protocol and then use the currently-available peers to initiate HTTP conversations outside the gossip layer. To this purpose, `gossip` provides a `getPeers` and `getPeers'` functions, but they are:

1. Not exposed;
2. Very `HyParView` specific.

As part of this ticket we should probably expose these two in `Oscoin.P2P`, but in a flavour such that the fact we are using `HyParView` is not leaked.

**Comment by kim** [comment]
`Oscoin.P2P` encapsulates `Network.Gossip.IO.Run`, which currently only exports `broadcast`. It can easily also export `getPeers`/`getPeers'`, which in turn would allow to add those to the `MonadBroadcast` (or kill this class entirely and export delegating actions at the top level).
