### ISSUE TITLE
 Extend the gossip protocol to advertise its HTTP API port during handshake

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/oscoin#536]
## Problem

In order to implement node syncing (see #531) we need a way to get our active peers and use the HTTP API to fetch the information we need. We already have a `getPeers` and `getPeers'` functions available, but they return (at most) the `SockAddr` the gossip protocol is communicating on, which is hardly suitable for HTTP traffic (modulo clunky and buggy multiplexing). 

## Solution/implementation plan

We should extend the handshake mechanism between peers to also announce the port the HTTP API is listening to. This way, we can try reusing the existing `SockAddr` the `Peer` data structure provide to kickoff HTTP traffic.

## Blockers

(cc @kim) Currently a `SockAddr` has these constructors:

```haskell
SockAddrInet !PortNumber!HostAddress |  
-- | --
SockAddrInet6 !PortNumber!FlowInfo !HostAddress6!ScopeID |  
SockAddrUnix String
``` 

This means that if we pattern match on the already-available `SockAddr` and we get a `SockAddrUnix`, we are out of luck. I do wonder if it would be better to extend our `Peer` type with something like:

```haskell
data Peer n = Peer
    { peerNodeId :: n
    , peerAddr   :: SockAddr
    , peerHttpAPI :: SockAddr
   } deriving (Eq, Show)
```

So that we don't have to do any guessing.

**Comment by kim** [comment]
The `n` (i.e. `peerNodeId`) is where you can stick additional data. Thus, the handshake would need to be adapted to result in a `(PortNumber, NodeId c)`.

An alternative approach would be to connect to the gossip port (ie. simply the `SockAddr` you get back from `getPeers`), and layer another handshake protocol which gives you back _just_ the port number (and closes all connections immediately). Even better would be to make this additional protocol hand you back a socket which talks HTTP, but that is obviously more complicated.

**Comment by adinapoli-mndc** [comment]
Thanks for the valuable insights, @kim! I am approaching the end of my working day and I am starting not to reason clearly, but my gut feeling is that eventually something like a `(HostAddress, PortNumber, NodeId c)` is what we'll end up having (we can ofc simplify this to have `(SockAddr, NodeId c)` and alias the former to something like `type HttpApiParams` or similar).

I would perhaps exclude the more complicated approach as that could imply spinning up and keeping open a socket, which in nature is fragile, as it could be reset/closed abruptly, not leaving us any option in terms of disaster recovery. If we go with the `(Port,Address)` solution, instead, we have the option to re-issue a failed request, for example.
