### ISSUE TITLE
Add lookupHeight and lookupHeightRange to both the Blockstore reader and HTTP APIs

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/oscoin#550]
## Problem

In order to implement #531 , we do need a way to fetch blocks from peers, given a block `Height` or a range. This corresponds to the `lookupByHeight` and `lookupByHeightRange` from the spec, but we don't have these functions yet, neither in the `BlockStoreReader` nor in the HTTP API.

## Solution/implementation plan

Even though our internal interface might change later (i.e. by introducing a `BlockTree`), we do want to get syncing implemented relatively soon, which means the most pragmatic approach is to implement these two functions directly on the existing `BlockStore`. As written in the specs, we can even emulate `lookupByHeightRange` using the minimal API and change things later.

We do also want to expose the relevant endpoints in our HTTP API, so that clients can consume it.

### A note on the HTTP API

If we were to do things properly (ala RESTful way) we would ideally expose a `GET /blocks` endpoint which would return the first 50 (or so, upper limit to be decided) blocks and then implement these two queries in terms of filters, as in:

```
GET /blocks?height=GTE[10]&height=LTE[20]
```

(Note how the above would also allow us to scrap `/blockchain/best` in favour of a more resource-centric API).

However, doing this properly is a non-trivial amount of work and I am not sure we have time for it now, but if we disregard the complication of a fully-fledged query system for the filtering, we could _at least_ implement an ad-hoc filter like `height[10,20]` and perhaps when we have a bit more capacity sit at the table and implement this properly.

@cloudhead @geigerzaehler @kim thoughts?

**Comment by geigerzaehler** [comment]
👍 on exposing `lookupByHeight` and `lookupByHeightRange` on the API.

Regarding the HTTP API I would forgo the a generic RESTful implementation. Since we only have this one way of querying blocks it would lead to bikeshedding about the parameter encoding and lots of code for parameter encoding and decoding. I’d suggest and endpoint of the form `/blocks/by-height-range?minHeight=10&maxHeight100` or whatever you like to call it.

**Comment by cloudhead** [comment]
:+1: 

I wouldn't go crazy on the REST, but an adhoc filter like you suggest might be a nice middle ground.

**Comment by adinapoli-mndc** [comment]
I have also realised that if we want to efficiently support light clients, we will probably also need something like `lookupHeaderByHeight` and `lookupHeaderByHeightRange` (pick-your-favourite-name), but in the meantime we can simply implement this client side by throwing away the block body after fetching the full block (which is obviously inefficient & wasteful).

**Comment by geigerzaehler** [comment]
To spare us some effort in implementing and maintaining I would prefer to not implement `lookupHeaderByHeightRange` at all if it is not needed.

**Comment by adinapoli-mndc** [comment]
> To spare us some effort in implementing and maintaining I would prefer to not implement lookupHeaderByHeightRange at all if it is not needed.

I _think_ we might need it for light clients, but not in the near future and we can surely have a seat and think about how we can minimise boilerplate. For now I agree, let's implement only the ability to fetch full blocks, and let's revisit this after devnet.
