### ISSUE TITLE
Move transaction validaiton to the Mempool

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/oscoin#553]
## Problem

Transaction validation is the process of checking that a transaction is properly signed. Invalid transactions should be rejected by the Ledger API and not make their way into the Mempool. Currently the logic responsible for that lives in `Oscoin.API.HTTP.Handlers.submitTransaction`. This blocks #552 and does not guarantee that the Mempool does not contain invalid transaction.

## Solution/implementation plan

I propose to do transaction validation as part of the insertion into the Mempool. `Mempool.addTxs :: [tx] -> m ()` will be replaced with
~~~haskell
class Mempool m c tx where
  addTx :: tx -> m (Either (TxValidationError c tx) ())
~~~

`TxValidationError c tx` is a type family similar to `TxOutput`. The Mempool will be instantiated with the transaction validation.

**Comment by kim** [comment]
How about leaving validation and storage decoupled, but wrap the argument in a `newtype` which "proves" that the `tx` has been validated?

Given the polymorphism of our ... everything, I would expect that this would require a separate typeclass. This isn't so bad, as it could actually allow the newtype wrapper to be an associated type, where the (concrete) constructor is hidden at the definition site.

**Comment by geigerzaehler** [comment]
> How about leaving validation and storage decoupled, but wrap the argument in a `newtype` which "proves" that the `tx` has been validated?

Would this look like this?
~~~haskell
class Mempool m c tx where
  addTx :: ValidatedTx c tx -> m ()
  lookupTx :: m tx

type family ValidatedTx c tx

newtype ValidatedOscoinTx c = ValidatedOscoinTx (OscoinTx c)

type instance ValidatedTx c (OscoinTx c) = ValidatedOscoinTx c

validateOscoinTx :: OscoinTx c -> Either OscoinTxValidationError (ValidatedOscoinTx c)
~~~

The code above does not use a type class and would require passing validator as a parameter to the HTTP API for example.

Using a type class would address this but would make it harder to switch the validation although we arguably won’t need that.

Thoughts @cloudhead and @adinapoli-mndc?

**Comment by kim** [comment]
Yeah, that works, too, as long as the `ValidatedOscoinTx` is not exported from the module where `validateOscoinTx` is defined.
