### ISSUE TITLE
Make it easier to set `--beneficiary`

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/oscoin#570]
## Problem

Since #547 we provide an address through the `--beneficiary` option to run the node. It is not clear how to get a valid address. I currently use the REPL and the `Oscoin.Crypto.Address` module. We should make this easier, however.

I don’t have an idea how to tackle this. We should think about this as part of the tooling around user keys and accounts.

**Comment by cloudhead** [comment]
Good point - perhaps having an address generator in the CLI would be useful.

**Comment by kim** [comment]
Technically, we also need to store the corresponding secret key somewhere.
