### ISSUE TITLE
Log output on cloud instances

### ISSUE THREAD

**Issue by kim** [oscoin/oscoin#572]
Logs aggregated by GCP's Stackdriver look like this:

```
2019-05-21 16:51:15.899 CEST
[96minfo [0m | mined block block_hash=2DrjgbKpP1aNbLnz1kQzBubeuSekWGTrffHTT88SCmmCrezMr8 ns="node" loc="Oscoin.Node:121:22"
 
Expand all | Collapse all {
 insertId:  "1qpq9l3g2ir1tuh"  
 jsonPayload: {
  container_id:  "c4ae3397b1a9abfca264c539dcb737a5aa1851a39bf5f4207029f93aa84fbce6"   
  message:  "[96minfo [0m | mined block block_hash=2DrjgbKpP1aNbLnz1kQzBubeuSekWGTrffHTT88SCmmCrezMr8 ns="node" loc="Oscoin.Node:121:22"
"   
  stream:  "stderr"   
 }
 labels: {
  compute.googleapis.com/resource_name:  "0b79a73e1518"   
 }
 logName:  "projects/opensourcecoin/logs/cos_containers"  
 receiveTimestamp:  "2019-05-21T14:51:18.955495345Z"  
 resource: {
  labels: {
   instance_id:  "1629246337835447054"    
   project_id:  "opensourcecoin"    
   zone:  "europe-west1-b"    
  }
  type:  "gce_instance"   
 }
 timestamp:  "2019-05-21T14:51:15.899358941Z"  
}
```

This is obviously not ideal. While it is possible to tweak the log aggregation configuration until it yields something more useful, this would be highly specific to the deployment platform, and thus anyone trying to deploy to their environment would have to put in this effort, too. We should instead try to make the log output more suitable to server deployments. Improvements include:

* [ ] Allow turning off colored output, even when running in development mode
* [ ] Extend the namespacing functionality to add more tags regardless of logging context. This should probably include: bound IP address, node id

**Comment by adinapoli-mndc** [comment]
Definitely not opposed to kill the colored output -- it was a bit of a gimmick to begin with 😁 . I think that apart from the colours what is also bothersome for logging aggregation is that we format in a slightly different format (in a similar fashion of what this [post](https://brandur.org/logfmt) describes, the "human" section).

This makes me think wether or not it would actually be useful to separate the "local development" environment from the "clown development environment", as I can see how the human readable format might be slightly more useful when staring at logs on our own machines, but un-optimal for cloud deployments.

**Comment by kim** [comment]
Now looks like this:

```
{
 insertId:  "1f2cvp9g4agv82f"  
 jsonPayload: {
  CONTAINER_ID:  "d4a9e3dc3467"   
  CONTAINER_ID_FULL:  "d4a9e3dc3467c50b364b752649d99961555b6d73e62064b910c9f35aeb76d62a"   
  CONTAINER_NAME:  "oscoin"   
  CONTAINER_TAG:  "d4a9e3dc3467"   
  MESSAGE:  "level="I" msg="mined block" block_hash=2Drjgb5QyKk4zovGEafCcSspUppjbDEURvLLaBGJGVa2WuWmXT ns="node" loc="Oscoin.Node:122:22""   
  PRIORITY:  "3"   
  SYSLOG_IDENTIFIER:  "d4a9e3dc3467"   
  _BOOT_ID:  "81e8c8136107405898dbad0898e48ffa"   
  _CAP_EFFECTIVE:  "3fffffffff"   
  _CMDLINE:  "/usr/bin/dockerd --registry-mirror=https://mirror.gcr.io --host=fd:// --containerd=/var/run/containerd/containerd.sock"   
  _COMM:  "dockerd"   
  _EXE:  "/usr/bin/dockerd"   
  _GID:  "0"   
  _HOSTNAME:  "oscoin-node-devnet-56nh"   
  _MACHINE_ID:  "6c32cbf60ef9ade575544d3efd813be2"   
  _PID:  "356"   
  _SOURCE_REALTIME_TIMESTAMP:  "1559807447799096"   
  _SYSTEMD_CGROUP:  "/system.slice/docker.service"   
  _SYSTEMD_INVOCATION_ID:  "b28fc59196004ee4beb3103204543780"   
  _SYSTEMD_SLICE:  "system.slice"   
  _SYSTEMD_UNIT:  "docker.service"   
  _TRANSPORT:  "journal"   
  _UID:  "0"   
 }
 labels: {
  compute.googleapis.com/resource_name:  "83cd63949340"   
 }
 logName:  "projects/opensourcecoin/logs/cos_docker"  
 receiveTimestamp:  "2019-06-06T07:50:53.883018377Z"  
 resource: {
  labels: {
   instance_id:  "4286483913143625183"    
   project_id:  "opensourcecoin"    
   zone:  "europe-west3-a"    
  }
  type:  "gce_instance"   
 }
 timestamp:  "2019-06-06T07:50:47.799726Z"  
}
```

I think this is alright in terms of available metadata, but turning the `MESSAGE` into indexed fields would make it more useful. That's a separate ticket, though.

**Comment by adinapoli-mndc** [comment]
> I think this is alright in terms of available metadata, but turning the MESSAGE into indexed fields would make it more useful.

Yup -- would switching from a format which is not `logfmt` help here? I know that for example certain services (like Loggly, but I suspect that's similar for stackdriver) can recognise automatically certain formats in the payload and display things properly in the dashboard (if any).

**Comment by kim** [comment]
No, `stackdriver` doesn't perform any post-processing. Nothing in the multiple layers of ~~convolution~~indirection actually inspects the log message, except splitting on newline by the docker log driver. The only way is to configure fluentd to transform what it reads from journald before forwarding.
