### ISSUE TITLE
Reward beneficiary with block coinbase

### ISSUE THREAD

**Issue by cloudhead** [oscoin/oscoin#591]
### Problem

Block evaluation as implemented abstractly by `LedgerStore` is incompatible with
the evaluation required by the Oscoin ledger. This blocks the integration of OscoinTx (https://github.com/oscoin/oscoin/issues/568)

When evaluating a block (i.e. using the block data to produce a new state) the
Oscoin ledger will do the following.

1. Credit `blockDataBeneficiary` with the coinbase
2. Evaluate all transactions in turn using the `blockDataBeneficiary` as an
   additional input.

This means that the block evaluation function for `Block c tx s` 

~~~haskell
applyTx :: Beneficiary c -> tx -> TxState tx -> (TxState tx, TxOutput tx)
applyBeneficiary :: Beneficiary c -> TxState tx -> TxState tx
~~~

In our current system the `LedgerStore` handles block evaluation. The
`LedgerStore` only accepts an evaluation function of the type

~~~haskell
eval :: tx -> TxState tx -> Either EvalError (TxState tx, TxOutput tx)
~~~

This means that the `LedgerStore` is incompatible with the Oscoin ledger.

### Suggested Solution

Instead of the `LedgerStore` receiving and evaluator of the type given above it
will receive an evaluator of the type

~~~haskell
evalBlock :: Beneficiary c -> [tx] -> TxState tx -> (TxState tx, [TxOutput tx])
~~~

The Oscoin Ledger will provide a function of this type by combining `applyTx`
and `applyBeneficiary`.

In the code we would change the `Evaluator` type alias to the type of
`evalBlock`. In addition the legacy tx (defined in `Oscoin.Data.Tx`) and all the
test tx types would be changed to use the new eval block type.

**Comment by geigerzaehler** [comment]
@cloudhead: I took the liberty of updating the description with a couple more details.
