### ISSUE TITLE
CLI to verify consensus health

### ISSUE THREAD

**Issue by cloudhead** [oscoin/oscoin#592]
To verify the health of a cluster, we need a tool that:
* Get block header at a certain height
* Be able to query a node by IP
* Get the last N headers, by depth

**Comment by kim** [comment]
As a ???, I need this?

Aside: please note that the devnet instances are not reachable over the internet (modulo #587) currently.

**Comment by cloudhead** [comment]
As a DevOps (:trollface:) I need to check my Devnet is operating as expected :grimacing:

**Comment by cloudhead** [comment]
> Aside: please note that the devnet instances are not reachable over the internet (modulo #587) currently.

I guess for now we can run the CLI from inside GCP? Eventually we'll want to expose the HTTP API port to the internetz though.

**Comment by kim** [comment]
Well, as an Ingenieur de Voops, I’d prefer a more automated solution, which calls me back on Slack when something doesn’t work according to the OKRs :trollface:

But yeah, we assemble a doge image of the CLI on CI, so as a Business Owner, I could `docker run` that on a jump host

**Comment by geigerzaehler** [comment]
Superseded by #604
