### ISSUE TITLE
Make sure only one node mines in the devnet

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/oscoin#605]
## Problem

Consensus and the protocol don’t work in the presence of forks at the moment. This means we will run the network with only one miner.

## Solution

- [x] Add a cli flag for the node that disables mining
- [ ] Update the continuous deployment pipeline so that the devent runs with only one miner.

**Comment by adinapoli-mndc** [comment]
I volunteer to tackle the first bit, as once we merge #647 it's gonna be very easy.

**Comment by adinapoli-mndc** [comment]
Part I has been completed here: https://github.com/oscoin/oscoin/pull/652

Now the tricky bit would be to orchestrate the deployment scripts so that only one node actually mines. @kim , what's the path of least resistance here?
