### ISSUE TITLE
Disable miner when syncing the first time

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/oscoin#628]
While testing node syncing and consensus, I did wonder the following: should the miner produce blocks even though syncing is in progress? It seems to me that this shouldn't be the case: while technically eventually nodes should reach consensus, it simply looks wasteful to me: we are mining blocks on a potentially very stale tip, only to throw them away (forever) once we start chasing the correct chain.

In order start the miner _a posteriori_, we could potentially extend the sync interface with an `onReady` callback that could be called once we finished syncing the first time. This would require a small adjustment in the syncing interface, but it would also avoid keep around mutable state or worse do something with MVars (like using one to block the miner up until we finished syncing).

If we implement the `onReady` idea, one would wire everything inside `node/Main.hs` and only when we are ready, we would spawn the miner (which runs in an async thread anyway).

Incidentally, it occurred to me we could use `onReady` also to fix #588: In this case `onReady` would also (likely) update a `Tvar` which the HTTP API can then later read to answer the question: is the node ready or not? It would also mitigate all @kim's concerns about rollabacks and the remote tip being a moving target.

@cloudhead @kim @geigerzaehler thoughts?

**Comment by kim** [comment]
I would welcome if the node would not fully start up until a first round of syncing was complete, for the reasons given. I’m not sure, however, if that is sound during a network partition.

**Comment by geigerzaehler** [comment]
Sounds reasonable to me to not mine while syncing.
