### ISSUE TITLE
Improve node sync for non-optimal consensus and potential adversarial behaviour

### ISSUE THREAD

**Issue by adinapoli-mndc** [oscoin/oscoin#651]
## Summary

_Our current node sync works well only if the majority (if not all) the active peers are in agreement, which might not be the case in production. On top of that, it doesn't account for adversarial behaviour when splitting work between peers in `syncBlock`. I propose we modify the syncing algorithm (and the spec) as explained below to account for that._

## Problem

While conducting some local experiments, I did unravel a flaw of the current implementation of `syncBlocks`, for which I am going to post only a stripped down version:

```haskell
syncBlocks rng = do
    ctx <- ask
    let fetcher = scDataFetcher ctx
    withActivePeers $ \ activePeers ->

        lift $ runConduit $
               C.yieldMany (workDistribution activePeers)
            .| C.mapM (fetchBlocks fetcher >=> notifyUpstreamConsumers ctx)
            .| C.concat
            .| C.iterM (fetchMissing fetcher activePeers ctx)
            .| C.sinkNull
```

My laudable goal here was to split work across peers, so that we wouldn't overload a particular peer with tons of requests and that could in future be made parallel with relatively little effort. However, doing this height-based work-split is quite dangerous: in case _not all the peers reached consensus_, we could get back from a peer a particular fragment of a chain which is either stale (i.e. a rollback occurred), totally bogus (dishonest player) or simply a divergent chain (for any reason whatsoever). In such scenario, we are not doing the consensus layer any favour; we are sending it a bunch of uncorrelated chain fragments, with the likely outcome that the node being synced won't reach consensus (ever).

To illustrate this better, let's consider the following scenario (taken from a real experiment): we have 3 nodes: `node1` has the longest chain of 100 blocks, `node2` is on a divergent fork and `node3` is the node about to start syncing. Below let's find the `local_height` for all the three:

| Node name | Local Height |
|-----------|--------------|
| Node 1    | 100          |
| Node 2    | 80           |
| Node 3    | 60           |

When `node3` starts syncing, it requests the best remote tip to `node1` and `node2`. If you recall the algorithm, we pick the block with most frequency or, in case of draws, the highest one. Here `node1` and `node2` will return different blocks, but `node1` has the highest, so we start the sync by calling `syncBlocks` on the range `(61,100)` inclusive.

**Now, here is the problem**: we divide the work between `node1` and `node2` equally, but some (or all) the slices associated to `node2` will be relevant to a completely different chain respect to `node1`, which means that, as a result, `node3` won't receive a meaningful, consistent chain, and might be able to apply some blocks here and there. The rest, will be put in the orphanage.

What is worst is that perhaps `node3` 's local height might be able to advance of a bunch of blocks (either due to `node3` 's miner or by serendipitous block application) but the process will repeat similarly during the next "tick" of the sync algorithm.

While in principle the node should be able to _eventually_ recover from this by piggybacking on gossip's block retransmission, it looks to me a lame way of syncing blocks.

## Solution/implementation plan

First of all, let's get the elephant out of the room: despite my original intention was to maximise download speed and parallelism, I have now realised this is a fool's errand because (as "the internet" warned us already) even if we maximise the network throughput the syncing bottleneck is always going to be I/O bound, because we will need to apply and validate each block, and each call to `dispatchBlockSync` acquires a mutex on the orphanage, so everything happens sequentially. While we could in the future mitigate this with checkpoints (ala Parity) for now "correct" triumphs "fast".

With this in mind, here is my proposal, which is articulated in two steps. It doesn't require a complete overhaul of the syncing (for which the API won't change at all) but this would be merely internal.

During the first step, the node will compute what we can call the `commonChainHeight`: in order to actually fetch the block it needs, the nodes has to `A)` understand it's on a fork and `B)` how many blocks it has to fetch. If you recall the example I have posted above, let's assume that `node3` was also on a fork (to spice things up). When `node3` starts, we would run this `commonChainHeight` function which would eventually return the _height_ *all* the peers share in common, i.e. the height which correspond to a block which hash matches for *all* peers. Once this height has been acquired, the node can proceed to actually request the blocks in the range `(commonHeight + 1, bestRemoteTip)`, essentially as before.

Step 2 would involve changing the implementation of `syncBlocks`. Rather than trying to fetch the blocks in chunks based on a height range, we would focus on a classic iterative algorithm where we would start from `bestRemoteTip` and, for each block, request to _all peers, in a round robin fashion_, the block at hash `blockPrevHash`. We can obviously stop as soon as the block is found, skipping unnecessary HTTP calls. This is easy to do as our HTTP API already exposes such endpoint. If the block cannot be retrieved immediately, we have no choice but to wait and retry (either a fixed number of times or with a timeout). If we cannot fetch a block, we simply stop and restart the sync (i.e wait for the next "tick" of the endless loop) to give time to either the peer topology to adjust or for the main chain to reconcile.

## commonChainHeight implementation details

Implementing this function piggybacks on ideas from other projects. Essentially `node3` would ask all its peers for the `blockHash` corresponding to the block at height `60` (remember the table, it's the height we start after a reboot). If we get perfect agreement (i.e. all the hash matches), we are done. If not, we backtrack the height using a fibonacci sequence, so we would request heights 59,59,58,57,55,52,... up until a fixed limit (it could be 2016 or simply configurable on the `SyncContext`). If we cannot ever reach agreement.. see the section below.

## commonChainHeight and adversarial behaviours
 
There is a complication when implementing `commonChainHeight`: if one of our peers is dishonest (or simply not in agreement) we might end up backtracking past the limit without finding a suitable common height. In this scenario, I propose to do what (for example) `grin` does: we *start back from genesis*. The rationale would be that if we didn't reach an agreement it means something is off, either with the consensus or with the network in general (perhaps we are under attack), so the most conservative choice is to resume syncing from scratch.

## commonChainHeight and its variations

One might ask: why not implement `commonChainHeight` such that we don't require perfect agreement but we take the height of the block which root hash matches for _most peers_? We could do that, however it doesn't work that well for small clusters; if we have a group of 3 nodes like the one I have just presented, now we might have that (for example) `node1` and `node2` are in disagreement (i.e. `node2` is dishonest or on a very stale fork). In this situation, we don't have enough active peers to be able to resolve the ambiguity, and we cannot meaningfully pick `node1` or `node2` without having an oracle that knows `node1` is the "good" node (alas we don't have such oracle).

_Having said that_, the probability of *not* finding a `commonChainHeight` after the full backtrack window is very rare and it's likely to happen only in case of dishonest peers (which are the exceptions, not the rule). Even a node on a fork lagging severely behind should conceivably have some stale-but-far-away-from-genesis height, so agreement should be reached most of the times. If it doesn't it means our consensus is buggy, but that's a separate issue 😁 

cc @cloudhead @kim @geigerzaehler

**Comment by adinapoli-mndc** [comment]
> Step 2 would involve changing the implementation of syncBlocks. Rather than trying to fetch the blocks in chunks based on a height range, we would focus on a classic iterative algorithm where we would start from bestRemoteTip and, for each block, request to all peers, in a round robin fashion, the block at hash blockPrevHash

Actually, this is not going to work unfortunately, as it has the serious drawback that we won't produce a valid main chain up until the minute we would download the fork block between `commonChainHeight` and `commonChainHeight + 2`, which would also means our orphanage would grow (almost) unbounded, no good.

Other projects solved this by having a "forward pointer" to each block stored in the DB which would also allow them to request the block going _forward_, so that they could download blocks oldest-to-newest, but we can't.

I will have to think about this a bit more.

**Comment by kim** [comment]
Yeah this step 2 seems a bit odd to me, too: this is essentially what we (currently) get via gossip.

I am wondering if there is a way to decide on-the-fly which of the chains to follow à la [ZipSource](https://hackage.haskell.org/package/conduit-1.3.1.1/docs/Data-Conduit.html#t:ZipSource). Say we have calculated `commonChainHeight` as you suggest, and then request `(commonChainHeight + 1, bestRemoteTip)` from **all** of them, expecting the responses to be in **forward** order (ie. `[commonChainHeight + 1, commonChainHeight + 2, ..., commonChainHeight + n]`). Now we can proceed sequentially while all block(header)s are equal.

**Comment by adinapoli-mndc** [comment]
Thanks for chiming in @kim . Yes, that is a viable algorithm, although the predominant cost is the fact we have to hit _all our peers no matter what_. I don't have a clue if Gossip's active peers set is capped but I can imagine that if we have hundreds of them, this might be expensive.

Having said that, I am reaching the conclusion that you cannot meaningfully pick the right chain unless you know a priori which hashes to download. I was going to propose a schema where you would still download by height, requesting each time `commonChainHeight + 1, commonChainHeight + 2 , ...` but also crucially validating that `blockHash currentTip === blockPrevHash downloadedBlock`.

However, this is flawed as well: we could download by accident a block from a fork, and now we are stuck: we are forced to follow the bogus/forked chain.

This led me to the conclusion than indeed we should explore Kim's lead, which is also similar to what BTC does -- nodes exchange info between each other at at some point a node is given "the next 500 block hashes to download". I guess we have no choice but doing something similar.

**Comment by kim** [comment]
> I don't have a clue if Gossip's active peers set is capped

Yes, that's the point ;) It's 5 by default, could be maybe 10-20 in a large network.

**Comment by adinapoli-mndc** [comment]
Gotcha, so it's not humongous -- good 😉

**Comment by geigerzaehler** [comment]
I have a couple of questions.

> Once this height has been acquired, the node can proceed to actually request the blocks in the range `(commonHeight + 1, bestRemoteTip)`, essentially as before.

What do you mean by “essentially as before”? Do you mean doing a range-based query distributed to all peers? This seems to contradict the paragraph that follows where you describe backtracking from `bestRemoteTip`.

> Essentially `node3` would ask all its peers for the `blockHash` corresponding to the block at height `60`

If I understand this correctly an upper bound for `commonChainHeight` is the chain height of the node that is syncing, right? This means that for a new node we start at genesis and this makes the backtracking from the best remote infeasible.

> One might ask: why not implement `commonChainHeight` such that we don't require perfect agreement but we take the height of the block which root hash matches for _most peers_? We could do that, however it doesn't work that well for small clusters; if we have a group of 3 nodes like the one I have just presented, now we might have that (for example) `node1` and `node2` are in disagreement (i.e. `node2` is dishonest or on a very stale fork). In this situation, we don't have enough active peers to be able to resolve the ambiguity, and we cannot meaningfully pick `node1` or `node2` without having an oracle that knows `node1` is the "good" node (alas we don't have such oracle).

Your counterexample for the majority working mentions two peers that disagree. If my reading of the example is correct (node 2 is on a very stale fork), using the common chain height gives worse behavior, because node 2 is included in the calculation of the common chain height. We also don’t need to use majority every time. If there is a tie, we could use strict common chain. With three peers a majority agreement is already a lot better.

There are also some more problems that we might want to consider when finding a solution. For example what do we do if the node that has the best chain actually sends invalid blocks? How do we recover from that. And what do we do if we are in a partition and _all_ peers are on a fork?

I think it would be helpful to come up with a list of scenarios that node syncing should work under to help guide the discussion.
